services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: social_media
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/

volumes:
    db_data:
